#!/bin/bash

sudo apt update -y
sudo apt upgrade -y

echo "Instalando editor Neovim y plugins"
sudo apt install vim -y
sudo apt-get install neovim -y

mkdir ~/.config > /dev/null
mkdir ~/.config/nvim/ > /dev/null
VIMINIT=~/.vim/ | source $VIMINIT 
echo "Se establecio VIMINIT en '$VIMINIT'"

sudo echo "so ~/.vim/.vimrc">~/.vimrc
sudo echo "so ~/.vim/.vimrc">~/.config/nvim/init.vim

echo "Instalando vim-plug en el sistema..."
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

echo "Instalando plugins..."
sudo apt install python
pip install -U setuptools
pip install 'python-language-server[all]'
cp ~/.vim/shell/coc-settings.json ~/.config/nvim/

sudo apt install nodejs
curl -sL install-node.vercel.app/lts | bash
npm i -g sql-language-server

nvim -c ":PlugInstall" -c ":CocInstall coc-sh coc-go coc-html coc-java coc-tsserver coc-json coc-pyright coc-jedi coc-vetur" | bash 

echo "Instalación finalizada."

